- src/App.css
- src/components/Footer.tsx
- src/components/MainComponent.tsx
- src/components/VideoFriesComponent.tsx
- src/pages/Index.tsx
MobProgrammed:
Fixed main Display on Index page
Added Video adds on sides on Index Page
> Video fries

- src/App.tsx
- src/components/Navbar.tsx
DET FINNS EN TEMP DEV NAVBAR <3
/Kram Joel Hanna
> G2-102: Skapa en home-knapp & About-knapp som navigerar en till sidan

- src/components/SidesComponent.tsx
Added a function to convert MainResponse to ProductInfoData in preparation of shoppingcart implementation.
> Prepared Sides component for shoppingcart

- package-lock.json
- src/assets/drinkMotivation.json
- src/components/CartButton.tsx
- src/components/NavigationButton.tsx
- src/components/ProductInfo.tsx
- src/pages/DrinkSelect.tsx
- src/services/CocktailInfoService.ts
What we have done:
- We added functionality that remembers correct main when selected, thus gives us the correct recommended drink for that burger
- Added information about why it the drink is perfect with the burger
- Hao and Alex
> G2-78, G2-79 & G2-113

- src/App.tsx
- src/components/CartProductList.tsx
- src/components/CocktailPanel.tsx
- src/components/MainComponent.tsx
- src/components/SidesComponent.tsx
- src/components/VideoWrapper.tsx
- src/pages/Index.tsx
- src/styles.scss
> Added no drink/sides and videofries on all pages

- src/API/CocktailFetch.tsx
- src/components/CartProductList.tsx
- src/components/DrinkCarousel.tsx
- src/components/VideoWrapper.tsx
- src/pages/About.tsx
- src/styles.scss
> About box, CSS Fix and Cart-Count fix

- src/components/CartProductList.tsx
- src/styles.scss
> G2 122 kryss knapp

- src/App.tsx
- src/components/BreadCrumbs.tsx
- src/components/BreadCrumbsPageProvider.tsx
- src/components/CocktailMiniComponent.tsx
- src/components/MainComponent.tsx
- src/components/NavigationButton.tsx
- src/components/SidesComponent.tsx
- src/styles.scss
Added functionality to cocktails that is not recommended and also breadcrumbs
With Alexander and Caroline
> G2 115 valfri drink

- src/components/CartProductList.tsx
- src/styles.scss
Fixed animation on delete from cart
// Hanna and Joel
> G2 124 animation on delete

- src/components/CartProductList.tsx
- src/styles.scss
> fixed cart size

- src/components/CocktailMiniComponent.tsx
- src/components/DrinkCarousel.tsx
- src/components/MainComponent.tsx
- src/components/ProductInfo.tsx
- src/components/SidesComponent.tsx
- src/components/VideoFriesComponent.tsx
- src/pages/About.tsx
> G2 150 adding alt

- src/App.tsx
- src/components/CartContext.tsx
- src/components/CartProductList.tsx
- src/components/OrderConfirmation.tsx
- src/pages/ConfirmationPage.tsx
- src/styles.scss
Added order confirmation, navigation and empties cart when "pay" button is pressed.
> G2 165 order confirmation

- src/components/CartProductList.tsx
> Added opacity to text and price when quantity reaches 0

- src/components/CartProductList.tsx
- src/components/PageHistoryProvider.tsx
- src/styles.scss
Added a button to take the user to the front-page when clicked. Added functionality to Pay and Add menu button to clear pagehistory.
> G2 175, 173 - Add Menu button and clear page history

- src/components/BackButton.tsx
- src/components/CartContext.tsx
- src/components/NavigationButton.tsx
- src/components/PageHistoryProvider.tsx
- src/services/PageHistoryService.ts
Back button now works with removing item-quantity and item from cart.
> Back button product removal

- src/components/CocktailPanel.tsx
- src/pages/DrinkSelect.tsx
when burgerId is null there is a button for no drink
> G2 157 design3 rader drinkar

- src/App.tsx
- src/components/CocktailMiniComponent.tsx
- src/components/CocktailPanel.tsx
- src/components/NavigationButton.tsx
- src/components/SoftDrinkComponent.tsx
- src/pages/DrinkSelect.tsx
- src/pages/SoftDrink.tsx
Added soft drinks, made API call, made soft drink component, fixed links and navigationpaths
With Joel
> G2-182: User story done

- src/styles.scss
Changed background color to the right one.
> New background color

- src/App.css
- src/App.tsx
- src/components/CocktailMiniComponent.tsx
- src/components/CocktailPanel.tsx
- src/components/DrinkCarousel.tsx
- src/components/Header.tsx
- src/components/MainComponent.tsx
- src/components/NextButton.tsx
- src/components/Salad.tsx
- src/components/SidesComponent.tsx
- src/components/SoftDrinkComponent.tsx
- src/pages/ShoppingCart.tsx
- src/styles.scss
Had to change how we set the size on our different pages.
> G2-242_Adjusting page size

- src/components/CartProductList.tsx
- src/pages/DrinkSelect.tsx
- src/pages/ShoppingCart.tsx
- src/styles.scss
> G2 217 shopping cart as wireframe

- src/components/CartProductList.tsx
- src/components/CartQuantity.tsx
- src/components/CocktailMiniComponent.tsx
- src/components/CocktailPanel.tsx
- src/components/DrinkCarousel.tsx
- src/components/MainComponent.tsx
- src/components/NextButton.tsx
- src/components/ProductInfo.tsx
- src/components/SidesComponent.tsx
- src/components/SoftDrinkComponent.tsx
- src/styles.scss
Fixed the colors and some minor other stuff
> G2 243 change colors
